use strict;
use FindBin;
$ENV{EZ_CLI_BASHRC} //= "$FindBin::Bin/../../../.bashrc";
use warnings;
use IO::Pty;
use IO::Select;
use Time::HiRes qw(time sleep);
use File::Temp qw(tempdir);
$ENV{LC_ALL}='C';
$ENV{TERM}='xterm-256color';
my ($pty, $pid, $buf, $selector);
# A transparent space may contain one star, with color/style transitions.
my $gap=qr/(?:\e\[[0-9;]*m)*[ *+.](?:\e\[[0-9;]*m)*/;
sub start_case {
  my ($mode) = @_;
  $pty = IO::Pty->new;
  $pty->set_winsize($mode eq "many" ? 12 : 24,80,0,0);
  $pid = fork();
  die 'fork failed' unless defined $pid;
  if (!$pid) {
    $pty->make_slave_controlling_terminal;
    my $slave = $pty->slave;
    open STDIN, '<&', $slave or die $!;
    open STDOUT, '>&', $slave or die $!;
    open STDERR, '>&', $slave or die $!;
    close $pty;
    exec 'bash', '--noprofile', '--norc', '-i', "$FindBin::Bin/fixtures/terminal.bash", $mode;
    die $!;
  }
  $pty->close_slave;
  $selector=IO::Select->new($pty);
  $buf='';
}
sub pump {
  my ($seconds)=@_;
  my $end=time+$seconds;
  while (time < $end) {
    for my $fh ($selector->can_read(0.05)) {
      my $bytes=sysread($fh,my $chunk,65536);
      return unless $bytes;
      $buf.=$chunk;
    }
  }
}
sub expect {
  my ($pattern,$label)=@_;
  my $end=time+5;
  while ($buf !~ $pattern && time<$end) {pump(0.05)}
  die "FAIL $label\n$buf\n" unless $buf =~ $pattern;
}
sub send_keys { syswrite($pty,$_[0]); pump(0.15); }
sub plain { my $text=shift; $text =~ s/\e\[[0-9;?]*[A-Za-z]//g; return $text; }
sub read_file {
  open my $file, '<', $_[0] or die $!;
  local $/;
  return <$file>;
}
sub finish {
  expect(qr/TEST_DONE/,'finished');
  waitpid($pid,0);
  die "child failed: $?\n$buf" if $?;
  close $pty;
}
start_case('input_echo');
expect(qr/INPUT_WINDOW/,'redraw input window');
send_keys("\e[A");
expect(qr/\e\[1mThree/,'up during redraw selects last option');
die 'arrow key echoed during redraw' if index($buf, '^[[A') >= 0 || index($buf, "\e[A") >= 0;
send_keys(("\e[A" x 6)."\n");
expect(qr/SELECTED=2 STATUS=0/,'queued arrows preserve selection');
die 'queued arrow keys echoed' if index($buf, '^[[A') >= 0 || index($buf, "\e[A") >= 0;
expect(qr/TTY_RESTORED/,'terminal input modes restored');
finish();
print "PASS arrows during redraw and queued repeats stay silent; terminal modes restored\n";
start_case('chooser');
expect(qr/▲\/▼:${gap}Move/,'initial menu');
die 'selected option is not bold' unless $buf =~ /\e\[1mOne/;
die 'animated circle markers missing' unless plain($buf) =~ /●[ *+.]One/ && plain($buf) =~ /○[ *+.]Two/;
my @before=($buf =~ /(\d\d:\d\d:\d\d)/g);
my $idle_marker=length $buf;
pump(2.2);
my $idle_output=substr($buf,$idle_marker);
die 'clock tick repainted or cleared the whole menu' if $idle_output =~ /\e\[H|\e\[2[JK]/;
die 'animated foreground painted the original pink underlay' if $buf =~ /\e\[38;5;177m/;
my @after=($buf =~ /(\d\d:\d\d:\d\d)/g);
die 'clock did not advance' unless @after>1 && $after[-1] ne $before[0];
my $animation_marker=length $buf;
# Include the first sweep; updates must arrive between full clock redraws.
pump(3.0);
my $animation_output=substr($buf,$animation_marker);
die 'missing-focus recovery repaint was lost' unless $animation_output =~ /\e\[H/;
die 'recovery repaint restored the original title color' if $animation_output =~ /\e\[38;5;177m/;
my @overlay_frames=split /\e\[0m/, $animation_output;
my $moving_frames=grep {/\e\[\d+;\d+H(?:\e\[0;\d+m)?\e\[38;2;/} @overlay_frames;
die 'star animation did not produce intermediate frames' unless $moving_frames > 10;
send_keys("\e[B");
expect(qr/\e\[1mTwo/,'down highlights second option');
send_keys("\n");
expect(qr/SELECTED=1 STATUS=0/,'enter chooses second');
die 'cursor not restored' unless $buf =~ /\e\[\?25h/;
finish();
print "PASS arrow selection, bold styling, live seconds, cursor cleanup\n";
print "PASS clock updates avoid full redraws and original-color underlays\n";
start_case('static');
expect(qr/▲\/▼:${gap}Move/,'static fallback menu');
die 'static mode emitted an animation overlay' if $buf =~ /\e\[\d+;\d+H(?:\e\[0;\d+m)?\e\[38;2;/;
die 'static circle markers missing' unless plain($buf) =~ /●[ *+.]One/ && plain($buf) =~ /○[ *+.]Two/;
send_keys("\e[A\n");
expect(qr/SELECTED=2 STATUS=0/,'static navigation');
finish();
print "PASS animation frames and opt-out with static navigation\n";
start_case('submenu_geometry');
expect(qr/GEOMETRY/,'submenu rendered');
pump(0.2);
my $submenu_plain=plain($buf);
my ($submenu_prefix)=$submenu_plain =~ /\r([^\r\n]*?)●[ *+.]Short/;
die 'submenu marker column did not center the longest label' unless defined($submenu_prefix) && length($submenu_prefix)==25;
my ($above_options)=$submenu_plain =~ /GEOMETRY[^\n]*\n(.*?)●/s;
my ($below_options)=$submenu_plain =~ /longer option[^\n]*\n(.*?)▲\/▼\/◀\/▶/s;
die 'submenu spacing is not balanced around its options' unless defined($above_options) && defined($below_options)
  && (()=$above_options =~ /\n/g)==1 && (()=$below_options =~ /\n/g)==1;
send_keys("\e");
expect(qr/SELECTED= STATUS=130/,'submenu escape');
finish();
print "PASS submenu options center as one block using the longest label\n";
start_case('main_geometry');
expect(qr/Codex:.*Resume/,'main menu with a long session preview');
pump(0.2);
my ($preview_prefix)=plain($buf) =~ /\r([^\r\n]*?)●[ *+.]New Terminal/;
die 'session-name preview changed main menu centering' unless defined($preview_prefix) && length($preview_prefix)==28;
send_keys("\e");
finish();
print "PASS main menu centers without its session-name preview\n";
start_case('submenu_geometry');
expect(qr/GEOMETRY/,'submenu for Back navigation');
expect(qr/\e\[38;5;250m◀—/,'inactive Back arrow is gray');
send_keys("\e[D");
expect(qr/\e\[38;5;255m\e\[1m◀— Back/,'Left focuses a bold white Back');
die 'Back focus did not dim the options' unless $buf =~ /\e\[38;5;250mShort/;
send_keys("\e[C\n");
expect(qr/SELECTED=0 STATUS=0/,'Right returns to option and Enter selects');
finish();
start_case('submenu_geometry');
expect(qr/GEOMETRY/,'submenu for Back selection');
send_keys("\e[D\n");
expect(qr/SELECTED= STATUS=130/,'Enter on Back returns');
finish();
print "PASS Left/Right Back focus and selection in submenus\n";
start_case('chooser');
expect(qr/Enter\/Space:${gap}Select/,'Space selection hint');
send_keys("\e[B ");
expect(qr/SELECTED=1 STATUS=0/,'Space selects highlighted main-menu option');
finish();
start_case('submenu_geometry');
expect(qr/GEOMETRY/,'submenu for Space selection');
send_keys(' ');
expect(qr/SELECTED=0 STATUS=0/,'Space selects highlighted submenu option');
finish();
start_case('submenu_geometry');
expect(qr/GEOMETRY/,'submenu Back focus for Space selection');
send_keys("\e[D ");
expect(qr/SELECTED= STATUS=130/,'Space selects Back');
finish();
print "PASS Space selects focused menu options and Back\n";
start_case('duration');
expect(qr/Alpha/,'selected session duration');
pump(0.2);
my $duration_tick_marker=length $buf;
pump(2.2);
my $duration_tick_output=substr($buf,$duration_tick_marker);
die 'uptime tick repainted option rows or the star field' if $duration_tick_output =~ /\r|\e\[H|\e\[2J/;
my $duration_plain=plain($buf);
my @durations=($duration_plain =~ /\((\d+:\d{2})\)/g);
die 'selected session duration did not increment' unless @durations > 1 && $durations[-1] ne $durations[0];
my $back_focus_marker=length $buf;
send_keys("\e[D");
my $back_focus_frame=plain(substr($buf,$back_focus_marker));
my ($back_session_row)=$back_focus_frame =~ /(○[ *+.]Alpha[^\r\n]*)/;
die 'Back focus kept the selected session timer' unless defined($back_session_row)
  && $back_session_row !~ /\(\d+:\d{2}\)/;
die 'Back focus repainted the star field' if substr($buf,$back_focus_marker) =~ /\e\[H|\e\[2J/;
my $session_focus_marker=length $buf;
send_keys("\e[C");
my $session_focus_frame=plain(substr($buf,$session_focus_marker));
die 'session timer did not return after leaving Back focus'
  unless $session_focus_frame =~ /●[ *+.]Alpha \(\d+:\d{2}\)/;
my $unselected_marker=length $buf;
send_keys("\e[A");
my $unselected_frame=substr($buf,$unselected_marker);
die 'session selection repainted the star field' if $unselected_frame =~ /\e\[H|\e\[2J/;
my $unselected_duration=plain($unselected_frame);
die 'unselected session did not revert to its plain name' unless $unselected_duration =~ /○[ *+.]Alpha/;
send_keys("\e");
finish();
print "PASS selected session uptime increments and disappears on selection change\n";
start_case('duration_static');
expect(qr/Alpha/,'static duration menu');
pump(0.2);
my ($timed_prefix)=plain($buf) =~ /\r([^\r\n]*?)●[ *+.]Alpha \(\d+:\d{2}\)/;
my $plain_marker=length $buf;
send_keys("\e[A");
my ($plain_prefix)=plain(substr($buf,$plain_marker)) =~ /\r([^\r\n]*?)○[ *+.]Alpha/;
die 'timestamp changed the session option column' unless defined($timed_prefix) && defined($plain_prefix)
  && length($timed_prefix)==length($plain_prefix) && length($timed_prefix)==32;
send_keys("\e");
finish();
print "PASS timestamp visibility keeps the option column fixed\n";
start_case('name_cursor');
expect(qr/Session name/,'name cursor field');
send_keys("AB\e[DX\e[CY\n");
expect(qr/NAME=AXBY STATUS=0/,'name cursor moves left and right for insertion');
finish();
start_case('path_root');
expect(qr/> \//,'root path initially visible');
send_keys("\e[D\e[D\e[D");
my $root_movement=plain($buf);
die 'parent navigation produced a double slash' if $root_movement =~ /> \/\//;
send_keys("\x15");
pump(0.2);
die 'empty path hint missing after clear' unless plain($buf) =~ /Type or navigate to a directory/;
send_keys("\e");
finish();
print "PASS editable name cursor and stable directory root\n";
for my $key ("\e[C", "\t") {
  start_case('path_root_child');
  expect(qr/> \/tm/,'root child prefix');
  my $start=length $buf;
  send_keys($key);
  my $selection=plain(substr($buf,$start));
  die 'selected root child was not displayed as /tmp' unless $selection =~ /> \/tmp/;
  die 'selected root child contained a double slash' if $selection =~ /> \/\/tmp/;
  send_keys("\n");
  expect(qr/PATH=\/tmp STATUS=0 VALID=1/,'selected root child resolves to /tmp');
  finish();
}
print "PASS root child selection displays and returns a canonical path\n";
my $new_dir_root=tempdir(CLEANUP=>1);
my $new_dir="$new_dir_root/new dir +-=~()[] \$ !#";
$ENV{TEST_PATH_INPUT}=$new_dir_root;
start_case('path_create');
expect(qr/Start directory/,'new-directory picker');
die 'new-directory action is missing' unless plain($buf) =~ /Add new directory/;
send_keys("\e[D");
expect(qr/\e\[38;5;255m\e\[1m◀— Back/,'Left from Use this directory focuses Back');
send_keys("\e[B");
expect(qr/\e\[1mAdd/,'Down from Back selects the available add-directory action');
send_keys("\n");
expect(qr/New directory name/,'Add new directory opens a name textbox');
expect(qr/\e\[38;5;160m> /,'empty directory name has a red prompt');
send_keys('invalid/name');
expect(qr/\e\[38;5;160m> invalid\/name/,'slash is invalid in a directory name');
send_keys("\n");
die 'invalid directory name was accepted' if $buf =~ /PATH=/;
send_keys("\x15new dir +-=~()[] \$ !#");
expect(qr/\e\[38;5;255m> new dir/,'valid directory name has a white prompt');
send_keys("\n");
expect(qr/STATUS=0 EXISTS=1/,'new directory was created');
die 'picker returned the wrong new directory' unless plain($buf) =~ /PATH=\Q$new_dir\E STATUS=0 EXISTS=1/;
die 'new directory is absent' unless -d $new_dir;
finish();
$ENV{TEST_PATH_INPUT}="$new_dir_root/prefilled";
start_case('path_create');
expect(qr/Start directory/,'new-directory path prefix');
send_keys("\e[B\n");
expect(qr/New directory name/,'typed candidate opens the name textbox');
expect(qr/> prefilled/,'candidate name is prefilled');
send_keys("\e");
expect(qr/Start directory/,'Escape returns from name textbox');
die 'Escape created the candidate directory' if -e "$new_dir_root/prefilled";
send_keys("\e[B\n\n");
expect(qr/PATH=\Q$new_dir_root\E\/prefilled STATUS=0 EXISTS=1/,'prefilled directory name creates the directory');
finish();
$ENV{TEST_PATH_INPUT}="$new_dir_root/missing/child";
start_case('path_create');
expect(qr/\e\[38;5;160m> /,'invalid new-directory path has a red prompt');
send_keys("\e[B\n");
die 'invalid path created a directory' if -d "$new_dir_root/missing";
die 'invalid path was accepted' if $buf =~ /PATH=/;
send_keys("\e[D");
expect(qr/\e\[38;5;255m\e\[1m◀— Back/,'Left from new-directory action focuses Back');
my $inactive_marker=length $buf;
send_keys("\e[B");
my $inactive_frame=substr($buf,$inactive_marker);
die 'Down from Back focused a disabled action' if $inactive_frame !~ /\e\[38;5;255m\e\[1m◀— Back/;
die 'disabled action lost its dark gray style' if $inactive_frame !~ /\e\[38;5;242m\e\[9mAdd/;
send_keys("\n");
expect(qr/STATUS=130/,'Enter on path-picker Back cancels');
finish();
start_case('path_root_child');
expect(qr/> \/tm/,'directory suggestion before parent navigation');
my $parent_marker=length $buf;
send_keys("\e[B\e[D");
my $parent_frame=plain(substr($buf,$parent_marker));
die 'Left from a directory suggestion focused Back' if $parent_frame =~ /◀— Back/;
die 'Left from a directory suggestion did not open its parent' unless $parent_frame =~ /> \/ /;
send_keys("\e");
finish();
print "PASS directory creation, invalid-path rejection, and context-sensitive Back focus\n";
start_case('chooser');
expect(qr/▲\/▼:${gap}Move/,'menu');
send_keys("\eOA\n");
expect(qr/SELECTED=2 STATUS=0/,'application arrow wraps upward');
finish();
start_case('chooser');
expect(qr/▲\/▼:${gap}Move/,'menu');
send_keys("\e");
expect(qr/SELECTED= STATUS=130/,'escape cancels');
finish();
print "PASS arrow wrap and Escape\n";
start_case('chooser');
expect(qr/▲\/▼:${gap}Move/,'main menu for Right key');
send_keys("\e[C");
die 'Right selected a menu item' if $buf =~ /SELECTED=/;
send_keys("\n");
expect(qr/SELECTED=0 STATUS=0/,'Enter selects the highlighted main menu item');
finish();
print "PASS Right leaves the main menu selection unchanged; Enter selects\n";
my $switcher_test=tempdir(CLEANUP=>1);
$ENV{TEST_SWITCHER_LOG}="$switcher_test/switcher.log";
$ENV{TEST_MONITOR_FILE}="$switcher_test/monitor";
open my $switcher_file, '>', $ENV{TEST_SWITCHER_LOG} or die $!;
close $switcher_file;
$ENV{TEST_SWITCHER_READY}=1;
start_case('switcher_menu');
expect(qr/Dashboard/,'switcher dashboard menu entry');
die 'dashboard entry missing' unless plain($buf) =~ /Codex Switcher: Dashboard/;
die 'automatic switching option should be hidden' if plain($buf) =~ /Automatic Account Switching/;
pump(0.5);
die 'readiness was polled by the menu' unless read_file($ENV{TEST_SWITCHER_LOG}) eq '';
send_keys("\e[B\e[B\n");
expect(qr/MONITOR_ATTACHED/,'monitor attached outside tmux');
die 'monitor was mistaken for a Codex session' if plain($buf) =~ /Codex: Resume \(switcher\)/;
send_keys("\n");
my $monitor_plain=plain($buf);
die 'monitor session was not reused' unless (()=$monitor_plain =~ /MONITOR_CREATED/g)==1 && (()=$monitor_plain =~ /MONITOR_ATTACHED/g)==2;
die 'monitor used a reserved switcher command' unless read_file($ENV{TEST_SWITCHER_LOG}) eq '';
send_keys("\e");
finish();
$ENV{TMUX}='fake-client';
start_case('switcher_tmux');
expect(qr/Dashboard/,'monitor entry inside tmux');
send_keys("\e[B\e[B\n");
expect(qr/MONITOR_SWITCHED/,'existing tmux client switched to monitor session');
die 'nested tmux attach used inside tmux' if $buf =~ /MONITOR_ATTACHED/;
send_keys("\e");
finish();
delete $ENV{TMUX};
$ENV{TEST_SWITCHER_READY}=0;
start_case('switcher_ready');
expect(qr/Dashboard/,'monitor entry with future-ready stub');
die 'automatic switching option shown despite being hidden' if plain($buf) =~ /Automatic Account Switching/;
send_keys("\e");
finish();
delete $ENV{TEST_SWITCHER_READY};
delete $ENV{TEST_SWITCHER_LOG};
delete $ENV{TEST_MONITOR_FILE};
print "PASS switcher monitor availability, reuse, tmux modes, and hidden switching option\n";
start_case('many');
expect(qr/1-5 of 30/,'scroll window');
send_keys("\e[A\n");
expect(qr/SELECTED=29 STATUS=0/,'scroll wraps to last option');
finish();
print "PASS scrolling long menus\n";
my $session_dir=tempdir(CLEANUP=>1);
$ENV{TEST_SESSION_FILE}="$session_dir/session";
start_case('menu');
expect(qr/Codex:${gap}New${gap}Session/,'new session label when empty');
die 'missing dashboard is not continuously struck' unless $buf =~ /\e\[9mCodex Switcher: Dashboard\e\[0m/;
die 'missing dashboard explanation is absent' unless plain($buf) =~ /Codex Switcher: Dashboard[ *+.]\(unavailable\)/;
die 'sessions menu visible without sessions' if plain($buf) =~ /Codex: Sessions/;
send_keys("\e[B\n");
expect(qr/Session name/,'name prompt');
expect(qr/\e\[48;2;255;255;255m\e\[38;2;0;0;0mT/,'empty name hint has contrasting block cursor');
send_keys('Alpha');
expect(qr/> Alpha/,'typed session name visible');
expect(qr/Alpha\e\[48;2;255;255;255m\e\[38;2;0;0;0m /,'cursor follows entered name');
send_keys("\n");
expect(qr/Start directory/,'directory prompt');
expect(qr/> \/root/,'initial directory visible');
pump(0.2);
my $menu_entries=()=$buf =~ /\e\[\?1049h/g;
my $menu_exits=()=$buf =~ /\e\[\?1049l/g;
die 'menu screens leave the alternate screen between fields' unless $menu_entries==1 && $menu_exits==0;
my $field_marker=length $buf;
send_keys("\e[B");
my $field_update=substr($buf,$field_marker);
die 'directory movement clears the full screen' if $field_update =~ /\e\[2J/;
die 'directory movement repaints the full frame' if $field_update =~ /\e\[H/;
send_keys("\x15");
expect(qr/\e\[48;2;255;255;255m\e\[38;2;0;0;0mT/,'empty path hint has block cursor');
send_keys("/root\n");
expect(qr/CREATED:<new-session><-d><-P><-F><#\{session_id\}><-s><codex-Alpha><-c><\/root><-e><PATH=/,'launch directory and environment');
expect(qr/<satellite-codex><codex><--dangerously-bypass-approvals-and-sandbox>/,'direct launch arguments');
expect(qr/ATTACHED_CODEX/,'new session attaches');
expect(qr/Codex:${gap}Resume/,'resume label after detach');
expect(qr/Codex:${gap}Sessions/,'sessions menu after creation');
my $sessions_marker=length $buf;
send_keys("\e[B\n");
my $sessions_screen=plain(substr($buf,$sessions_marker));
die 'new session not first in picker' unless $sessions_screen =~ /\[new session\].*Alpha/s;
die 'session account fallback missing from picker' unless $sessions_screen =~ /Alpha[ *+.]\[unknown\]/;
die 'animated bold session title bar missing' unless $buf =~ /\e\[48;2;\d+;\d+;\d+m\e\[38;5;255m\e\[1m Codex: Sessions/;
send_keys("\e[B\n");
pump(0.5);
my $session_actions=plain($buf);
die 'session action menu missing' unless $session_actions =~ /Resume \(active for/;
die 'session account fallback missing from action title' unless $session_actions =~ /Alpha \[unknown\]/;
die 'action uptime is not gray and unbolded' unless $buf =~ /\e\[0m\e\[38;5;250m \(active for/;
send_keys("\n");
expect(qr/ATTACHED_CODEX.*ATTACHED_CODEX/s,'existing session attaches');
send_keys("\e");
send_keys("\e");
finish();
print "PASS Codex name input, directory navigation, creation, listing, and resume\n";
start_case('foreground');
expect(qr/SHELL JOBS/,'jobs menu');
expect(qr/Stopped/,'stopped job listed');
send_keys("\n");
expect(qr/JOB 1:/,'job actions');
send_keys("\n");
expect(qr/JOB_RESUMED_SUCCESSFULLY/,'foreground resume');
finish();
print "PASS foregrounding a stopped job in the calling shell\n";
start_case('jobs');
expect(qr/SHELL JOBS/,'jobs screen');
die 'all jobs action missing' unless plain($buf) =~ /Terminate all jobs/;
send_keys("\n");
expect(qr/JOB 1:/,'job actions');
send_keys("\e[B\n");
expect(qr/Termination requested for job %1/,'individual termination');
pump(0.3);
# Select the last action even if a terminating job is still listed.
send_keys("\e[A\n");
expect(qr/Termination requested for job %2/,'terminate remaining jobs');
pump(0.3);
# A final redraw may briefly include a terminating process; Escape returns.
send_keys("\e");
finish();
print "PASS individual and all-job termination\n";
open my $legacy, '>', $ENV{TEST_SESSION_FILE} or die $!;
print {$legacy} "codex\n";
close $legacy;
start_case('menu');
expect(qr/Codex:${gap}Resume${gap}\(codex\)/,'legacy codex resume label');
expect(qr/Codex:${gap}Sessions/,'legacy codex enables sessions menu');
my ($main_prefix)=plain($buf) =~ /\r([^\r\n]*?)●[ *+.]New Terminal/;
die 'main menu centering includes the resume session name' unless defined($main_prefix) && length($main_prefix)==19;
send_keys("\e[B\n");
expect(qr/ATTACHED_CODEX/,'resume action');
my $legacy_marker=length $buf;
send_keys("\e[B\n");
my $legacy_deadline=time+5;
while (plain(substr($buf,$legacy_marker)) !~ /\[new session\].*codex/s && time<$legacy_deadline) {pump(0.05)}
my $legacy_list=substr($buf,$legacy_marker);
die 'legacy codex missing from Sessions list' unless plain($legacy_list) =~ /\[new session\].*codex/s;
send_keys("\e");
send_keys("\e[A\e[A\n");
expect(qr/Ready when you are/,'New Terminal still leaves the menu');
finish();
delete $ENV{TEST_SESSION_FILE};
print "PASS existing Codex session resume/detach and return to the shell\n";
start_case('chooser');
expect(qr/▲\/▼:${gap}Move/,'menu before interrupt');
send_keys("\x03");
expect(qr/\e\[\?25h/,'cursor restored on Ctrl-C');
waitpid($pid,0);
close $pty;
print "PASS Ctrl-C cleanup\n";
start_case('chooser');
expect(qr/▲\/▼:${gap}Move/,'menu hints');
die 'Ctrl-L hint is still shown' if plain($buf) =~ /Ctrl-L/;
die 'alternate screen missing' unless $buf =~ /\e\[\?1049h/;
die 'focus reporting missing' unless $buf =~ /\e\[\?1004h/;
die 'premature screen cleanup' if $buf =~ /\e\[\?1049l/;
send_keys("\e[B");
expect(qr/\e\[1mTwo/,'selected before focus changes');
my $marker=length $buf;
send_keys("\e[O\e[I");
my $focus_output=substr($buf,$marker);
die 'focus-in did not repaint from home' unless $focus_output =~ /\e\[H.*\e\[1mTwo/s;
$marker=length $buf;
send_keys("\x0c");
die 'Ctrl-L still repaints' if substr($buf,$marker) =~ /\e\[H/;
$marker=length $buf;
$pty->set_winsize(12,36,0,0);
pump(1.3);
my $small_output=substr($buf,$marker);
# A frame composed before SIGWINCH can still be in flight. Check the latest
# complete repaint, which supersedes those bytes on the actual terminal.
my $small_home=rindex($small_output,"\e[H");
die 'resize did not repaint from home' if $small_home < 0;
$small_output=substr($small_output,$small_home);
die 'resize did not use compact title' unless plain($small_output) =~ /SATELLITE/;
die 'resize lost selection' unless $small_output =~ /\e\[1mTwo/;
die 'narrow screen still contains block title' if plain($small_output) =~ /#####  ###/;
$marker=length $buf;
$pty->set_winsize(24,80,0,0);
pump(1.3);
my $large_output=substr($buf,$marker);
die 'enlarging did not restore block title' unless plain($large_output) =~ /#####  ###/;
die 'enlarging lost selection' unless $large_output =~ /\e\[1mTwo/;
die 'relative vertical cursor movement remains' if $buf =~ /\e\[\d+[AB]/;
send_keys("\n");
expect(qr/SELECTED=1 STATUS=0/,'selection after focus and resize');
finish();
my $enters=()=$buf =~ /\e\[\?1049h/g;
my $exits=()=$buf =~ /\e\[\?1049l/g;
die "unbalanced alternate screen lifecycle: $enters/$exits" unless $enters==1 && $exits==1;
die 'focus mode not disabled' unless $buf =~ /\e\[\?1004l/;
print "PASS focus-in, ignored Ctrl-L, shrink/grow resize, preserved selection, and alternate-screen cleanup\n";
